# Generated by Django 4.0.3 on 2022-03-21 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_auto_20220316_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamplatform',
            old_name='names',
            new_name='name',
        ),
    ]
