# Generated by Django 4.0.3 on 2022-03-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='watchlist',
        ),
    ]
